TASK:
  NAME: "Method_Name"
  NOTES: "KaggleVersion_Notes"
  PROJECT: "CC_ReID"
  TAGS: ["dev", "train"]  
  MODE: "train"  # train / visualization
  DEVICE: "cuda"  
  SEED: 1

DATA:
  TRAIN_DATASET: "ltcc"
  TRAIN_ROOT: "/kaggle/input/sysu-mm01/SYSU_MM01/"
  MODE: "all" # all / indoor
  IMAGE_SIZE: [384, 192]
  BATCHSIZE: 32
  NUM_INSTANCES: 8
  TEST_BATCH: 128
  NUM_WORKERS: 0
  
MODEL:
  MODULE: "Lucky"   # Lucky / Baseline / B_IP
  BACKBONE_TYPE: "resnet50" # resnet50 / resnet50_ibn_a

OPTIMIZER:
  NAME: "Adam"
  TOTAL_TRAIN_EPOCH: 80
  LEARNING_RATE: 0.0005

SCHEDULER:
  NAME: "WarmupMultiStepLR"

TEST:
  EVAL_EPOCH: 2
  RESUME_TEST_MODEL: 119  
  TEST_MODE: "inter-camera" 

SAVE:
  OUTPUT_PATH: "results/outputs"

